name: 部署MkDocs站点

on:
  push:
    branches:
      - main  # 或者是你的默认分支名称，如master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: 部署文档
        run: mkdocs gh-deploy --force